backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 16;

fading = true;
fade-delta = 3;

corner-radius = 12;
frame-opacity = 0.8;

blur-method = "dual_kawase";
blur-strength = 3;

rules: ({
  match = "
    class_g = 'Firefox' ||
    class_g = 'Thunderbird' ||
    class_g = 'Tor Browser' ||
    class_g = 'gearlever'
  ";
  blur-background = false;
  shadow = false;
}, {
  match = "window_type = 'normal' && (
    class_g = 'Audacious' ||
    class_g = 'Thunar' ||
    class_g = 'VSCodium' ||
    class_g = 'Mousepad'
  )";
  opacity = 0.9
}, {
  match = "
    window_type = 'tooltip' ||
    window_type = 'dropdown_menu' ||
    window_type = 'menu' ||
    window_type = 'dialog' ||
    window_type = 'combo'
  ";
  opacity = 0.85;
}, {
  match = "window_type = 'popup_menu'";
  opacity = 0.90;
  shadow = false;
  blur-background = false;
})
